//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAnimeList.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserAnimeList.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the anime status is &quot;airing&quot;, &quot;aired from&quot; must be specified..
        /// </summary>
        public static string ANIME_AIRED_FROM_REQUIRED_WHEN_AIRING {
            get {
                return ResourceManager.GetString("ANIME_AIRED_FROM_REQUIRED_WHEN_AIRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the anime status is &quot;finished&quot;, &quot;aired from&quot; must be specified..
        /// </summary>
        public static string ANIME_AIRED_FROM_REQUIRED_WHEN_FINISHED {
            get {
                return ResourceManager.GetString("ANIME_AIRED_FROM_REQUIRED_WHEN_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;aired until&quot; date cannot be earlier than the &quot;aired from&quot; date..
        /// </summary>
        public static string ANIME_AIRED_UNTIL_EARLY_FROM {
            get {
                return ResourceManager.GetString("ANIME_AIRED_UNTIL_EARLY_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &quot;aired until&quot; is provided, &quot;aired from&quot; must also be provided..
        /// </summary>
        public static string ANIME_AIRED_UNTIL_FILLED_AIRED_FROM_NOT_FILLED {
            get {
                return ResourceManager.GetString("ANIME_AIRED_UNTIL_FILLED_AIRED_FROM_NOT_FILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the anime status is &quot;finished&quot;, &quot;aired until&quot; must be specified..
        /// </summary>
        public static string ANIME_AIRED_UNTIL_REQUIRED_WHEN_FINISHED {
            get {
                return ResourceManager.GetString("ANIME_AIRED_UNTIL_REQUIRED_WHEN_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An anime with this name is already registered..
        /// </summary>
        public static string ANIME_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("ANIME_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime name exceeds the 256-character limit..
        /// </summary>
        public static string ANIME_EXCEEDS_LIMIT {
            get {
                return ResourceManager.GetString("ANIME_EXCEEDS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid anime sorting direction..
        /// </summary>
        public static string ANIME_INVALID_SORT_DIR {
            get {
                return ResourceManager.GetString("ANIME_INVALID_SORT_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid anime sorting criteria..
        /// </summary>
        public static string ANIME_INVALID_SORT_FIELD {
            get {
                return ResourceManager.GetString("ANIME_INVALID_SORT_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The finished date cannot be earlier than the started date..
        /// </summary>
        public static string ANIME_LIST_DATE_FINISHED_EARLIER_DATE_STARTED {
            get {
                return ResourceManager.GetString("ANIME_LIST_DATE_FINISHED_EARLIER_DATE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This anime list entry already exists..
        /// </summary>
        public static string ANIME_LIST_ENTRY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ANIME_LIST_ENTRY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime list is invalid or was not found..
        /// </summary>
        public static string ANIME_LIST_INVALID {
            get {
                return ResourceManager.GetString("ANIME_LIST_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sorting direction..
        /// </summary>
        public static string ANIME_LIST_INVALID_SORT_DIR {
            get {
                return ResourceManager.GetString("ANIME_LIST_INVALID_SORT_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sorting criteria..
        /// </summary>
        public static string ANIME_LIST_INVALID_SORT_FIELD {
            get {
                return ResourceManager.GetString("ANIME_LIST_INVALID_SORT_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime status is invalid..
        /// </summary>
        public static string ANIME_LIST_INVALID_STATUS {
            get {
                return ResourceManager.GetString("ANIME_LIST_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name filter exceeds the maximum length of 256 characters..
        /// </summary>
        public static string ANIME_LIST_QUERY_EXCEEDED {
            get {
                return ResourceManager.GetString("ANIME_LIST_QUERY_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime score must be between 1 and 10..
        /// </summary>
        public static string ANIME_LIST_SCORE_INVALID {
            get {
                return ResourceManager.GetString("ANIME_LIST_SCORE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified anime was not found..
        /// </summary>
        public static string ANIME_NOT_FOUND {
            get {
                return ResourceManager.GetString("ANIME_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When premiered year is provided, premiered season must also be provided..
        /// </summary>
        public static string ANIME_PREMIERED_SEASON_REQUIRED {
            get {
                return ResourceManager.GetString("ANIME_PREMIERED_SEASON_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When premiered season is provided, premiered year must also be provided..
        /// </summary>
        public static string ANIME_PREMIERED_YEAR_REQUIRED {
            get {
                return ResourceManager.GetString("ANIME_PREMIERED_YEAR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime query exceeds the maximum length of 256 characters..
        /// </summary>
        public static string ANIME_QUERY_EXCEEDED {
            get {
                return ResourceManager.GetString("ANIME_QUERY_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more genres are duplicated..
        /// </summary>
        public static string DUPLICATED_GENRES {
            get {
                return ResourceManager.GetString("DUPLICATED_GENRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more studios are duplicated..
        /// </summary>
        public static string DUPLICATED_STUDIOS {
            get {
                return ResourceManager.GetString("DUPLICATED_STUDIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered on the platform..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email and/or password..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid episode count..
        /// </summary>
        public static string EPISODE_COUNT_INVALID {
            get {
                return ResourceManager.GetString("EPISODE_COUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the anime status is &quot;finished&quot;, the number of episodes must be provided..
        /// </summary>
        public static string EPISODE_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("EPISODE_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please sign in again to continue..
        /// </summary>
        public static string EXPIRED_SESSION {
            get {
                return ResourceManager.GetString("EXPIRED_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This genre is already registered..
        /// </summary>
        public static string GENRE_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("GENRE_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified genre was not found..
        /// </summary>
        public static string GENRE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENRE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime genres cannot be null..
        /// </summary>
        public static string GENRES_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("GENRES_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided image exceeds the maximum size (5 MB)..
        /// </summary>
        public static string IMAGE_EXCEEDS_FILE_SIZE {
            get {
                return ResourceManager.GetString("IMAGE_EXCEEDS_FILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image was provided..
        /// </summary>
        public static string IMAGE_NULL {
            get {
                return ResourceManager.GetString("IMAGE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following genres are invalid:.
        /// </summary>
        public static string INVALID_GENRES_IN_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_GENRES_IN_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID format..
        /// </summary>
        public static string INVALID_ID {
            get {
                return ResourceManager.GetString("INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided season is invalid..
        /// </summary>
        public static string INVALID_SEASON {
            get {
                return ResourceManager.GetString("INVALID_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON format..
        /// </summary>
        public static string INVALID_JSON {
            get {
                return ResourceManager.GetString("INVALID_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 6 to 50 characters long and contain at least three of the following: uppercase letters, lowercase letters, numbers, and symbols..
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request body is invalid or missing..
        /// </summary>
        public static string INVALID_REQUEST_BODY {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role claim..
        /// </summary>
        public static string INVALID_ROLE_CLAIM {
            get {
                return ResourceManager.GetString("INVALID_ROLE_CLAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a valid session. Please log in to access this feature..
        /// </summary>
        public static string INVALID_SESSION {
            get {
                return ResourceManager.GetString("INVALID_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following studios are invalid:.
        /// </summary>
        public static string INVALID_STUDIOS_IN_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_STUDIOS_IN_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication token..
        /// </summary>
        public static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password is incorrect..
        /// </summary>
        public static string LOGIN_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username (letters, numbers, underscores, and dashes only)..
        /// </summary>
        public static string NAME_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("NAME_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have access..
        /// </summary>
        public static string NO_ACCESS {
            get {
                return ResourceManager.GetString("NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication token was not provided..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only PNG, JPG, JPEG, and WEBP images are accepted..
        /// </summary>
        public static string ONLY_IMAGES_ACCEPTED {
            get {
                return ResourceManager.GetString("ONLY_IMAGES_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password does not match the current password..
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not be empty..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        public static string PASSWORDS_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORDS_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided anime source type is invalid..
        /// </summary>
        public static string SOURCE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("SOURCE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided anime status is invalid..
        /// </summary>
        public static string STATUS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("STATUS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This studio is already registered..
        /// </summary>
        public static string STUDIO_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("STUDIO_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio not found..
        /// </summary>
        public static string STUDIO_NOT_FOUND {
            get {
                return ResourceManager.GetString("STUDIO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime studios cannot be null..
        /// </summary>
        public static string STUDIOS_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("STUDIOS_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The synopsis exceeds the maximum length of 5,000 characters..
        /// </summary>
        public static string SYNOPSIS_EXCEEDS_LIMIT {
            get {
                return ResourceManager.GetString("SYNOPSIS_EXCEEDS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token has expired..
        /// </summary>
        public static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided anime type is invalid..
        /// </summary>
        public static string TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has no access..
        /// </summary>
        public static string USER_HAS_NO_ACCESS {
            get {
                return ResourceManager.GetString("USER_HAS_NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found in the database..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already registered on the platform..
        /// </summary>
        public static string USERNAME_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("USERNAME_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token version mismatch..
        /// </summary>
        public static string WRONG_TOKEN_VERSION {
            get {
                return ResourceManager.GetString("WRONG_TOKEN_VERSION", resourceCulture);
            }
        }
    }
}
