//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAnimeList.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserAnimeList.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the anime status is airing the aired from must be specified..
        /// </summary>
        public static string ANIME_AIRED_FROM_REQUIRED_WHEN_AIRING {
            get {
                return ResourceManager.GetString("ANIME_AIRED_FROM_REQUIRED_WHEN_AIRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the anime status is finished the aired from must be specified..
        /// </summary>
        public static string ANIME_AIRED_FROM_REQUIRED_WHEN_FINISHED {
            get {
                return ResourceManager.GetString("ANIME_AIRED_FROM_REQUIRED_WHEN_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime aired until cannot be earlier than aired from.
        /// </summary>
        public static string ANIME_AIRED_UNTIL_EARLY_FROM {
            get {
                return ResourceManager.GetString("ANIME_AIRED_UNTIL_EARLY_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When aired until is specified aired from must also be provided..
        /// </summary>
        public static string ANIME_AIRED_UNTIL_FILLED_AIRED_FROM_NOT_FILLED {
            get {
                return ResourceManager.GetString("ANIME_AIRED_UNTIL_FILLED_AIRED_FROM_NOT_FILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the anime status is finished the aired until must be specified..
        /// </summary>
        public static string ANIME_AIRED_UNTIL_REQUIRED_WHEN_FINISHED {
            get {
                return ResourceManager.GetString("ANIME_AIRED_UNTIL_REQUIRED_WHEN_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An anime with this name is already registered..
        /// </summary>
        public static string ANIME_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("ANIME_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime name exceeds the limit of 256 characters.
        /// </summary>
        public static string ANIME_EXCEEDS_LIMIT {
            get {
                return ResourceManager.GetString("ANIME_EXCEEDS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date finished cannot be earlier than date started..
        /// </summary>
        public static string ANIME_LIST_DATE_FINISHED_EARLIER_DATE_STARTED {
            get {
                return ResourceManager.GetString("ANIME_LIST_DATE_FINISHED_EARLIER_DATE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This anime list entry already exists..
        /// </summary>
        public static string ANIME_LIST_ENTRY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ANIME_LIST_ENTRY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime list invalid or not found..
        /// </summary>
        public static string ANIME_LIST_INVALID {
            get {
                return ResourceManager.GetString("ANIME_LIST_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status for the anime is invalid..
        /// </summary>
        public static string ANIME_LIST_INVALID_STATUS {
            get {
                return ResourceManager.GetString("ANIME_LIST_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime score must be between 1 and 10..
        /// </summary>
        public static string ANIME_LIST_SCORE_INVALID {
            get {
                return ResourceManager.GetString("ANIME_LIST_SCORE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified anime is not found..
        /// </summary>
        public static string ANIME_NOT_FOUND {
            get {
                return ResourceManager.GetString("ANIME_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string CODE_INVALID {
            get {
                return ResourceManager.GetString("CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code to reset your password is required..
        /// </summary>
        public static string CODE_RESET_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_RESET_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more genre is duplicated..
        /// </summary>
        public static string DUPLICATED_GENRES {
            get {
                return ResourceManager.GetString("DUPLICATED_GENRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more studio is duplicated..
        /// </summary>
        public static string DUPLICATED_STUDIOS {
            get {
                return ResourceManager.GetString("DUPLICATED_STUDIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered on the platform..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail and/or password..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search query cannot be empty..
        /// </summary>
        public static string EMPTY_QUERY {
            get {
                return ResourceManager.GetString("EMPTY_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid episode count..
        /// </summary>
        public static string EPISODE_COUNT_INVALID {
            get {
                return ResourceManager.GetString("EPISODE_COUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When anime is finished the anime episodes must be specified..
        /// </summary>
        public static string EPISODE_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("EPISODE_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is expired..
        /// </summary>
        public static string EXPIRED_CODE {
            get {
                return ResourceManager.GetString("EXPIRED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please log in again to continue..
        /// </summary>
        public static string EXPIRED_SESSION {
            get {
                return ResourceManager.GetString("EXPIRED_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This genre is already registered..
        /// </summary>
        public static string GENRE_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("GENRE_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified genre was not found..
        /// </summary>
        public static string GENRE_NOT_FOUND {
            get {
                return ResourceManager.GetString("GENRE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres for the anime cannot be null..
        /// </summary>
        public static string GENRES_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("GENRES_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following genres entered are invalid: .
        /// </summary>
        public static string INVALID_GENRES_IN_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_GENRES_IN_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id format..
        /// </summary>
        public static string INVALID_ID {
            get {
                return ResourceManager.GetString("INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON format..
        /// </summary>
        public static string INVALID_JSON {
            get {
                return ResourceManager.GetString("INVALID_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 - 50 characters long and contain at least three of the following: uppercase, lowercase, numbers and symbols...
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request body is invalid or missing..
        /// </summary>
        public static string INVALID_REQUEST_BODY {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role claim..
        /// </summary>
        public static string INVALID_ROLE_CLAIM {
            get {
                return ResourceManager.GetString("INVALID_ROLE_CLAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a valid session. Please log in to access this feature..
        /// </summary>
        public static string INVALID_SESSION {
            get {
                return ResourceManager.GetString("INVALID_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following studios entered are invalid: .
        /// </summary>
        public static string INVALID_STUDIOS_IN_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_STUDIOS_IN_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication token is invalid..
        /// </summary>
        public static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password is incorrect..
        /// </summary>
        public static string LOGIN_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username (letters, numbers, underscores and dashes only)..
        /// </summary>
        public static string NAME_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("NAME_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new name cannot be empty..
        /// </summary>
        public static string NEW_NAME_EMPTY {
            get {
                return ResourceManager.GetString("NEW_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new name cannot be the same as the old name..
        /// </summary>
        public static string NEW_NAME_EQUAL {
            get {
                return ResourceManager.GetString("NEW_NAME_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no access..
        /// </summary>
        public static string NO_ACCESS {
            get {
                return ResourceManager.GetString("NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication token was not provided..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images (PNG, JPG, JPEG) are accepted..
        /// </summary>
        public static string ONLY_IMAGES_ACCEPTED {
            get {
                return ResourceManager.GetString("ONLY_IMAGES_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is different from the current password..
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be empty..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords does not match..
        /// </summary>
        public static string PASSWORDS_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORDS_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search query must be at least three characters long..
        /// </summary>
        public static string QUERY_TOO_SHORT {
            get {
                return ResourceManager.GetString("QUERY_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime source type entered is not valid..
        /// </summary>
        public static string SOURCE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("SOURCE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime status entered is not valid..
        /// </summary>
        public static string STATUS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("STATUS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Studio is already registered..
        /// </summary>
        public static string STUDIO_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("STUDIO_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio not found..
        /// </summary>
        public static string STUDIO_NOT_FOUND {
            get {
                return ResourceManager.GetString("STUDIO_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studios for the anime cannot be null..
        /// </summary>
        public static string STUDIOS_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("STUDIOS_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified synopsis exceeds the maximum character length of 5000..
        /// </summary>
        public static string SYNOPSIS_EXCEEDS_LIMIT {
            get {
                return ResourceManager.GetString("SYNOPSIS_EXCEEDS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired..
        /// </summary>
        public static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime type entered is not valid..
        /// </summary>
        public static string TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has no access..
        /// </summary>
        public static string USER_HAS_NO_ACCESS {
            get {
                return ResourceManager.GetString("USER_HAS_NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found in database..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t access this resource..
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already registered on the platform..
        /// </summary>
        public static string USERNAME_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("USERNAME_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token version mismatch.
        /// </summary>
        public static string WRONG_TOKEN_VERSION {
            get {
                return ResourceManager.GetString("WRONG_TOKEN_VERSION", resourceCulture);
            }
        }
    }
}
